server:
  port: 9090

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
  server:
    enable-self-preservation: false
